Add issue templates
loqusion/hyprshade pull request #42
Opened 2024-07-08 15:29 UTC by HarshNarayanJha

Added new issue templates, one for `Bug report` and another for a `Feature request`.

2024-07-08 15:31 UTC, HarshNarayanJha commented
Hey @loqusion, here are the templates! Please review and see if everything seems right.

2024-07-11 15:41 UTC, HarshNarayanJha commented
Hey @loqusion, The Templates!

2024-07-11 15:56 UTC, loqusion requested changes

2024-07-11 16:22 UTC, HarshNarayanJha commented on .github/ISSUE_TEMPLATE/bug_report.md
> +- **Hyprshade config**: Please provide the contents of your `hyprshade.toml` file (generally at `$XDG_CONFIG_HOME/hypr/hyprshade.toml` or `~/.config/hypr/hyprshade.toml`, if not present then skip thi
Done!

2024-07-11 16:23 UTC, HarshNarayanJha commented on .github/ISSUE_TEMPLATE/bug_report.md
> +- **GPU (if any)**: [e.g. NVIDIA, AMD, Intel]
don't know a lot about nixpkgs and nixos though. if needed I can edit the message

- **Hyprshade Installation Method**: [e.g. pip, AUR, nixpkgs]

2024-07-11 16:26 UTC, HarshNarayanJha commented
> Oops, didn't know you had to click a button to finish a review

Oh! No worries.

2024-07-12 17:03 UTC, merged